import type { Poem } from "../../lib/types";
import { tangAnthologyPoems } from "./tang-anthology";

const definePoem = (
  poem: Omit<Poem, "translator" | "license">,
): Poem => ({
  ...poem,
  translator: "Moon Mood Tonight",
  license: "CC BY 4.0",
});

const curatedPoems: Poem[] = [
  definePoem({
    slug: "the-reeds",
    title: "The Reeds",
    originalTitle: "蒹葭",
    poet: "Anonymous",
    poetChinese: "佚名",
    dynasty: "Book of Songs",
    approximateDate: "c. 11th–7th century BCE",
    originalChinese: [
      ["蒹葭苍苍", "白露为霜", "所谓伊人", "在水一方"],
      ["溯洄从之", "道阻且长", "溯游从之", "宛在水中央"],
      ["蒹葭萋萋", "白露未晞", "所谓伊人", "在水之湄"],
      ["溯洄从之", "道阻且跻", "溯游从之", "宛在水中坻"],
      ["蒹葭采采", "白露未已", "所谓伊人", "在水之涘"],
      ["溯洄从之", "道阻且右", "溯游从之", "宛在水中沚"],
    ],
    translation: [
      [
        "The reeds are pale and lush;",
        "white dew has turned to frost.",
        "The one for whom I long",
        "is somewhere beyond the water.",
      ],
      [
        "I follow the current to seek them—",
        "the road is hard and long.",
        "I follow the current the other way:",
        "there they are, in the heart of the water.",
      ],
      [
        "The reeds grow thick and bright;",
        "the white dew is not yet dry.",
        "The one for whom I long",
        "waits somewhere by the water.",
      ],
      [
        "I follow the current to seek them—",
        "the path is steep and high.",
        "I follow the current the other way:",
        "there they are, upon an island in the water.",
      ],
      [
        "The reeds are dense and green;",
        "the white dew has not yet gone.",
        "The one for whom I long",
        "stands somewhere at the water’s edge.",
      ],
      [
        "I follow the current to seek them—",
        "the path winds without end.",
        "I follow the current the other way:",
        "there they are, on a shoal in the water.",
      ],
    ],
    moods: { longing: 1, wonder: 0.58, melancholy: 0.52 },
    themes: ["distance", "desire", "water", "searching"],
    image: "/poems/01-the-reeds.jpg",
    imageAlt: "A misty river marsh filled with pale reeds at dawn",
    introduction:
      "One of the most haunting love poems in the Book of Songs, built from repetition, mist, and an unreachable figure across the water.",
    interpretation:
      "It belongs to Longing because every movement brings the speaker closer in imagination while the beloved remains beautifully out of reach.",
  }),
  definePoem({
    slug: "long-long-the-road",
    title: "Long, Long the Road",
    originalTitle: "行行重行行",
    poet: "Anonymous",
    poetChinese: "佚名",
    dynasty: "Han dynasty",
    approximateDate: "1st–2nd century",
    originalChinese: [
      ["行行重行行", "与君生别离", "相去万余里", "各在天一涯"],
      ["道路阻且长", "会面安可知", "胡马依北风", "越鸟巢南枝"],
      ["相去日已远", "衣带日已缓", "浮云蔽白日", "游子不顾返"],
      ["思君令人老", "岁月忽已晚", "弃捐勿复道", "努力加餐饭"],
    ],
    translation: [
      [
        "On and on, and on again you go,",
        "alive, yet parted from me.",
        "More than ten thousand miles between us,",
        "each at a far end of the sky.",
      ],
      [
        "The road is blocked and long—",
        "how can we know when we will meet?",
        "The northern horse leans toward the north wind;",
        "the southern bird nests on a southern branch.",
      ],
      [
        "Each day you are farther away.",
        "Each day my robe hangs looser.",
        "Drifting clouds veil the bright sun;",
        "the wanderer does not turn back.",
      ],
      [
        "Thinking of you makes one grow old.",
        "Suddenly, the year is almost done.",
        "Say no more of being cast aside.",
        "Take care of yourself. Eat well.",
      ],
    ],
    moods: { longing: 0.98, solitude: 0.72, nostalgia: 0.68 },
    themes: ["separation", "travel", "time", "care"],
    image: "/poems/02-long-road.jpg",
    imageAlt: "A lone traveler receding along an ancient road at dusk",
    introduction:
      "From the Nineteen Old Poems, this work turns immense distance into intimate physical detail: a loosening robe, a clouded sun, a final wish to eat well.",
    interpretation:
      "Longing here is not abstract. It changes the body, stretches time, and finally becomes a quiet act of care for the absent person.",
  }),
  definePoem({
    slug: "drinking-wine-v",
    title: "Drinking Wine V",
    originalTitle: "饮酒·其五",
    poet: "Tao Yuanming",
    poetChinese: "陶渊明",
    dynasty: "Eastern Jin",
    approximateDate: "4th–5th century",
    originalChinese: [
      ["结庐在人境", "而无车马喧", "问君何能尔", "心远地自偏"],
      ["采菊东篱下", "悠然见南山", "山气日夕佳", "飞鸟相与还"],
      ["此中有真意", "欲辨已忘言"],
    ],
    translation: [
      [
        "I built my hut among the homes of men,",
        "yet hear no noise of cart or horse.",
        "You ask me how this can be:",
        "when the heart is distant, the place grows remote.",
      ],
      [
        "I pluck chrysanthemums beneath the eastern fence",
        "and quietly behold the southern hills.",
        "The mountain air is lovely at dusk;",
        "the birds return together.",
      ],
      [
        "Within these things, a deeper truth abides.",
        "I would explain—",
        "but I have forgotten the words.",
      ],
    ],
    moods: { stillness: 1, wonder: 0.62, joy: 0.45 },
    themes: ["retreat", "nature", "attention", "simplicity"],
    image: "/poems/03-drinking-wine.jpg",
    imageAlt: "Chrysanthemums by a quiet fence beneath distant southern mountains",
    introduction:
      "Tao Yuanming finds seclusion without leaving human society. The decisive distance is created by the mind, not by geography.",
    interpretation:
      "This is Stillness as a form of attention: the unforced sight of a mountain, birds returning, and meaning too complete for explanation.",
  }),
  definePoem({
    slug: "spring-river-flower-moon-night",
    title: "Spring River in the Flower Moon Night",
    originalTitle: "春江花月夜",
    poet: "Zhang Ruoxu",
    poetChinese: "张若虚",
    dynasty: "Tang dynasty",
    approximateDate: "7th–8th century",
    originalChinese: [
      ["春江潮水连海平", "海上明月共潮生", "滟滟随波千万里", "何处春江无月明"],
      ["江流宛转绕芳甸", "月照花林皆似霰", "空里流霜不觉飞", "汀上白沙看不见"],
      ["江天一色无纤尘", "皎皎空中孤月轮", "江畔何人初见月", "江月何年初照人"],
      ["人生代代无穷已", "江月年年望相似", "不知江月待何人", "但见长江送流水"],
      ["白云一片去悠悠", "青枫浦上不胜愁", "谁家今夜扁舟子", "何处相思明月楼"],
    ],
    translation: [
      [
        "The spring tide rises level with the sea;",
        "above the sea, the bright moon rises with the tide.",
        "It glitters on the waves for a thousand miles—",
        "where along the spring river is there no moonlight?",
      ],
      [
        "The river winds around a fragrant meadow;",
        "moonlight makes the flowering woods look dusted with snow.",
        "Frost seems to drift through the empty air unseen;",
        "the white sand of the riverbank disappears in light.",
      ],
      [
        "River and sky: one color, without a grain of dust.",
        "Alone in the clear heavens hangs the radiant moon.",
        "Who first stood by this river and saw the moon?",
        "In what first year did this river-moon shine on us?",
      ],
      [
        "Human generations come and go without end;",
        "year after year, the river-moon looks much the same.",
        "I do not know for whom the river-moon is waiting.",
        "I see only the long river carrying water away.",
      ],
      [
        "A single white cloud drifts slowly into distance;",
        "at Green Maple Shore, sorrow cannot be borne.",
        "Whose traveler floats tonight in a little boat?",
        "Where does someone ache with longing in a moonlit tower?",
      ],
    ],
    moods: {
      longing: 0.96,
      wonder: 1,
      solitude: 0.64,
      melancholy: 0.52,
    },
    themes: ["moon", "distance", "time", "love", "river"],
    image: "/poems/04-spring-river.jpg",
    imageAlt: "A luminous moon above a spring river and flowering branches",
    introduction:
      "A curated passage from a long Tang meditation in which river, moon, time, and separated lovers become part of one continuous field of light.",
    interpretation:
      "The poem holds Longing and Wonder together: human lives are brief and separated, yet the shared moon makes distance feel almost traversable.",
    excerpt: true,
  }),
  definePoem({
    slug: "autumn-evening-in-the-mountains",
    title: "An Autumn Evening in the Mountains",
    originalTitle: "山居秋暝",
    poet: "Wang Wei",
    poetChinese: "王维",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [
      ["空山新雨后", "天气晚来秋", "明月松间照", "清泉石上流"],
      ["竹喧归浣女", "莲动下渔舟", "随意春芳歇", "王孙自可留"],
    ],
    translation: [
      [
        "After fresh rain, the empty mountain;",
        "evening comes, and autumn is in the air.",
        "The bright moon shines between the pines;",
        "clear water flows over stones.",
      ],
      [
        "Voices of washerwomen return through bamboo;",
        "lotus leaves stir beneath a fishing boat.",
        "Let the spring fragrance fade if it must—",
        "here, my friend, you may remain.",
      ],
    ],
    moods: { stillness: 0.96, wonder: 0.64, joy: 0.42 },
    themes: ["mountains", "rain", "moon", "belonging"],
    image: "/poems/05-autumn-evening.jpg",
    imageAlt: "Moonlight through rain-washed pines above a clear mountain stream",
    introduction:
      "Wang Wei’s mountain evening is quiet without being empty: water, voices, bamboo, and a fishing boat all move within its calm.",
    interpretation:
      "Stillness is not silence here. It is a world in balance, alive enough that the speaker chooses to remain.",
  }),
  definePoem({
    slug: "bring-in-the-wine",
    title: "Bring in the Wine",
    originalTitle: "将进酒",
    poet: "Li Bai",
    poetChinese: "李白",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [
      ["君不见黄河之水天上来", "奔流到海不复回", "君不见高堂明镜悲白发", "朝如青丝暮成雪"],
      ["人生得意须尽欢", "莫使金樽空对月", "天生我材必有用", "千金散尽还复来"],
      ["烹羊宰牛且为乐", "会须一饮三百杯", "岑夫子", "丹丘生", "将进酒", "杯莫停"],
      ["与君歌一曲", "请君为我倾耳听", "钟鼓馔玉不足贵", "但愿长醉不复醒"],
      ["五花马", "千金裘", "呼儿将出换美酒", "与尔同销万古愁"],
    ],
    translation: [
      [
        "Have you not seen the Yellow River’s waters",
        "come down from heaven,",
        "rushing to the sea, never to return?",
        "Have you not seen bright halls mirror the grief of white hair—",
        "black silk at dawn, snow by nightfall?",
      ],
      [
        "When life opens its arms, drink joy to the full.",
        "Do not leave the golden cup empty beneath the moon.",
        "Heaven gave me gifts that must be put to use;",
        "a thousand gold pieces scattered will come again.",
      ],
      [
        "Cook the sheep, slaughter the ox—let us be merry.",
        "Tonight we must drink three hundred cups.",
        "Master Cen! Danqiu, my friend!",
        "Bring in the wine. Do not let your cups rest.",
      ],
      [
        "I will sing you a song;",
        "incline your ears and listen.",
        "Bells and drums, delicacies and jade are not worth cherishing.",
        "I only wish to stay drunk and never wake.",
      ],
      [
        "My dappled horse, my fur worth a thousand—",
        "call the boy, trade them for fine wine,",
        "and with you I will dissolve",
        "the sorrow of all ages.",
      ],
    ],
    moods: { courage: 1, joy: 0.92, melancholy: 0.35 },
    themes: ["wine", "time", "friendship", "defiance"],
    image: "/poems/06-bring-in-the-wine.jpg",
    imageAlt: "The Yellow River surging beneath storm clouds and golden light",
    introduction:
      "A curated passage from Li Bai’s great drinking song, where mortality is answered with friendship, extravagance, and radical confidence.",
    interpretation:
      "Its Courage is exuberant rather than solemn: life is brief, talent must be used, and ancient sorrow can be faced together.",
    excerpt: true,
  }),
  definePoem({
    slug: "climbing-high",
    title: "Climbing High",
    originalTitle: "登高",
    poet: "Du Fu",
    poetChinese: "杜甫",
    dynasty: "Tang dynasty",
    approximateDate: "767",
    originalChinese: [
      ["风急天高猿啸哀", "渚清沙白鸟飞回", "无边落木萧萧下", "不尽长江滚滚来"],
      ["万里悲秋常作客", "百年多病独登台", "艰难苦恨繁霜鬓", "潦倒新停浊酒杯"],
    ],
    translation: [
      [
        "The wind is sharp, the sky is high;",
        "apes cry in sorrow.",
        "Above clear sand and white water,",
        "birds wheel homeward.",
      ],
      [
        "Boundless leaves fall, rustling, rustling;",
        "the endless river rolls on and on.",
        "Ten thousand miles from home, always a guest in autumn;",
        "burdened by a lifetime of illness, I climb alone.",
      ],
      [
        "Hardship and grief have frosted my temples;",
        "worn down, I have newly put aside the wine cup.",
      ],
    ],
    moods: { solitude: 1, melancholy: 0.94, nostalgia: 0.8 },
    themes: ["autumn", "exile", "age", "river"],
    image: "/poems/07-climbing-high.jpg",
    imageAlt: "A lone poet above an autumn river filled with wind and falling leaves",
    introduction:
      "Written late in Du Fu’s life, the poem compresses illness, exile, autumn, and the vast Yangtze into eight tightly patterned lines.",
    interpretation:
      "Solitude expands from the solitary body to the whole landscape: falling leaves and the endless river make private grief feel cosmic.",
  }),
  definePoem({
    slug: "yellow-crane-tower",
    title: "Yellow Crane Tower",
    originalTitle: "黄鹤楼",
    poet: "Cui Hao",
    poetChinese: "崔颢",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [
      ["昔人已乘黄鹤去", "此地空余黄鹤楼", "黄鹤一去不复返", "白云千载空悠悠"],
      ["晴川历历汉阳树", "芳草萋萋鹦鹉洲", "日暮乡关何处是", "烟波江上使人愁"],
    ],
    translation: [
      [
        "Long ago, someone rode a yellow crane and vanished.",
        "Here, only Yellow Crane Tower remains.",
        "The yellow crane, once gone, never returned;",
        "for a thousand years, white clouds have drifted in vain.",
      ],
      [
        "Across the sunlit river, Hanyang’s trees stand clear;",
        "on Parrot Isle, the sweet grasses grow thick.",
        "At dusk, where is my homeland?",
        "Mist and waves upon the river deepen my sorrow.",
      ],
    ],
    moods: { nostalgia: 1, solitude: 0.72, melancholy: 0.68 },
    themes: ["home", "myth", "tower", "dusk"],
    image: "/poems/08-yellow-crane-tower.jpg",
    imageAlt: "An ancient river tower fading into a golden and violet dusk",
    introduction:
      "Legend, landscape, and homesickness meet at a famous river tower. The mythical crane is gone; clouds and the human need for home remain.",
    interpretation:
      "Nostalgia begins when a clear view cannot reveal the one place the speaker most wants to see.",
  }),
  definePoem({
    slug: "song-of-the-pipa",
    title: "Song of the Pipa",
    originalTitle: "琵琶行",
    poet: "Bai Juyi",
    poetChinese: "白居易",
    dynasty: "Tang dynasty",
    approximateDate: "816",
    originalChinese: [
      ["浔阳江头夜送客", "枫叶荻花秋瑟瑟", "主人下马客在船", "举酒欲饮无管弦"],
      ["醉不成欢惨将别", "别时茫茫江浸月", "忽闻水上琵琶声", "主人忘归客不发"],
      ["千呼万唤始出来", "犹抱琵琶半遮面", "转轴拨弦三两声", "未成曲调先有情"],
      ["大弦嘈嘈如急雨", "小弦切切如私语", "嘈嘈切切错杂弹", "大珠小珠落玉盘"],
      ["冰泉冷涩弦凝绝", "凝绝不通声暂歇", "别有幽愁暗恨生", "此时无声胜有声"],
      ["曲终收拨当心画", "四弦一声如裂帛", "东船西舫悄无言", "唯见江心秋月白"],
      ["同是天涯沦落人", "相逢何必曾相识"],
    ],
    translation: [
      [
        "At night by the Xunyang River, I saw a guest away.",
        "Maple leaves and reed flowers shivered in the autumn wind.",
        "We raised wine to drink, but had no strings or flutes.",
        "At farewell, the vast river steeped the moon.",
      ],
      [
        "Suddenly, over the water, we heard a pipa.",
        "The host forgot to leave; the guest did not depart.",
        "Called a thousand times, urged ten thousand, at last she came,",
        "still holding the pipa so it half concealed her face.",
      ],
      [
        "She turned the pegs and touched the strings—two, three notes;",
        "before the melody had formed, feeling was already there.",
        "The great strings clattered like sudden rain;",
        "the small strings whispered like lovers in a room.",
      ],
      [
        "Clatter and whisper tangled in her playing:",
        "large pearls and small pearls falling on a plate of jade.",
        "The icy spring grew cold; the strings seemed to freeze.",
        "At that moment, silence surpassed sound.",
      ],
      [
        "At the song’s end, four strings made one sound,",
        "like silk torn apart.",
        "The boats to east and west were silent.",
        "We saw only the white autumn moon in the river.",
      ],
      [
        "We are both wanderers fallen to the ends of the world—",
        "why should we have known each other before tonight?",
      ],
    ],
    moods: { melancholy: 1, solitude: 0.78, nostalgia: 0.72 },
    themes: ["music", "exile", "recognition", "autumn"],
    image: "/poems/09-song-of-the-pipa.jpg",
    imageAlt: "A pipa player in a small boat under moonlight on an autumn river",
    introduction:
      "A curated passage from Bai Juyi’s narrative masterpiece: a chance encounter, a musician’s performance, and the recognition between two displaced lives.",
    interpretation:
      "Melancholy becomes connection. The music gives private suffering a form that another person can finally understand.",
    excerpt: true,
  }),
  definePoem({
    slug: "the-jeweled-zither",
    title: "The Jeweled Zither",
    originalTitle: "锦瑟",
    poet: "Li Shangyin",
    poetChinese: "李商隐",
    dynasty: "Tang dynasty",
    approximateDate: "9th century",
    originalChinese: [
      ["锦瑟无端五十弦", "一弦一柱思华年", "庄生晓梦迷蝴蝶", "望帝春心托杜鹃"],
      ["沧海月明珠有泪", "蓝田日暖玉生烟", "此情可待成追忆", "只是当时已惘然"],
    ],
    translation: [
      [
        "The jeweled zither, for no reason, has fifty strings;",
        "each string, each bridge recalls one flowering year.",
        "At dawn, Master Zhuang was lost in a butterfly’s dream;",
        "King Wang entrusted his spring heart to the cuckoo.",
      ],
      [
        "Beneath a moonlit sea, bright pearls have tears.",
        "In Blue Field’s sun, warm jade gives birth to mist.",
        "Could this feeling have waited to become a memory?",
        "Even then, even there, it was already beyond knowing.",
      ],
    ],
    moods: { melancholy: 0.92, nostalgia: 0.86, wonder: 0.7 },
    themes: ["memory", "dream", "music", "mystery"],
    image: "/poems/10-jeweled-zither.jpg",
    imageAlt: "Zither strings dissolving into moonlit waves and blue jade mountains",
    introduction:
      "One of classical Chinese poetry’s most enigmatic works, moving through music, dream, myth, pearl, jade, memory, and bewilderment.",
    interpretation:
      "Its Melancholy cannot be reduced to one event. The feeling was already elusive while it was being lived.",
  }),
  definePoem({
    slug: "quiet-night-thought",
    title: "Quiet Night Thought",
    originalTitle: "静夜思",
    poet: "Li Bai",
    poetChinese: "李白",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [["床前明月光", "疑是地上霜", "举头望明月", "低头思故乡"]],
    translation: [
      [
        "Moonlight before my bed—",
        "I take it for frost on the ground.",
        "I lift my head and gaze at the bright moon;",
        "I lower it, thinking of home.",
      ],
    ],
    moods: { nostalgia: 1, longing: 0.82, solitude: 0.72 },
    themes: ["moon", "home", "night", "distance"],
    image: "/poems/04-spring-river.jpg",
    imageAlt: "Cold moonlight entering a quiet room",
    introduction:
      "Four plain lines create perhaps the best-known image of homesickness in Chinese poetry: moonlight crossing the floor of a distant room.",
    interpretation:
      "Nostalgia arrives through a small bodily movement—the head lifting toward the shared moon, then lowering toward an absent home.",
  }),
  definePoem({
    slug: "deer-enclosure",
    title: "Deer Enclosure",
    originalTitle: "鹿柴",
    poet: "Wang Wei",
    poetChinese: "王维",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [["空山不见人", "但闻人语响", "返景入深林", "复照青苔上"]],
    translation: [
      [
        "Empty mountain: no one in sight,",
        "only the echo of human voices.",
        "Returning sunlight enters the deep forest",
        "and shines again upon green moss.",
      ],
    ],
    moods: { stillness: 1, wonder: 0.7, solitude: 0.46 },
    themes: ["mountains", "light", "emptiness", "sound"],
    image: "/poems/05-autumn-evening.jpg",
    imageAlt: "A shaft of late sunlight touching moss in a deep forest",
    introduction:
      "Wang Wei makes emptiness perceptible through two interruptions: a voice without a visible speaker and late light touching moss.",
    interpretation:
      "Stillness is sharpened by what briefly enters it. Sound and light reveal how deep the quiet already was.",
  }),
  definePoem({
    slug: "river-snow",
    title: "River Snow",
    originalTitle: "江雪",
    poet: "Liu Zongyuan",
    poetChinese: "柳宗元",
    dynasty: "Tang dynasty",
    approximateDate: "9th century",
    originalChinese: [["千山鸟飞绝", "万径人踪灭", "孤舟蓑笠翁", "独钓寒江雪"]],
    translation: [
      [
        "Across a thousand mountains, no bird in flight.",
        "On ten thousand paths, no human trace.",
        "A solitary boat; an old man in straw cape and hat",
        "fishing alone in the cold river snow.",
      ],
    ],
    moods: { solitude: 1, stillness: 0.82, courage: 0.38 },
    themes: ["snow", "river", "endurance", "emptiness"],
    image: "/poems/07-climbing-high.jpg",
    imageAlt: "A solitary fishing boat on a cold river in falling snow",
    introduction:
      "Written during exile, this quatrain reduces the world to snow, absence, one boat, and one figure who continues his impossible task.",
    interpretation:
      "Solitude becomes austere self-possession: the landscape is emptied, but the fisherman remains.",
  }),
  definePoem({
    slug: "night-mooring-at-maple-bridge",
    title: "Night Mooring at Maple Bridge",
    originalTitle: "枫桥夜泊",
    poet: "Zhang Ji",
    poetChinese: "张继",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [["月落乌啼霜满天", "江枫渔火对愁眠", "姑苏城外寒山寺", "夜半钟声到客船"]],
    translation: [
      [
        "The moon sets, crows cry, frost fills the sky.",
        "River maples and fishing fires face my troubled sleep.",
        "Beyond the walls of Suzhou, from Cold Mountain Temple,",
        "the midnight bell reaches my traveling boat.",
      ],
    ],
    moods: { melancholy: 0.92, solitude: 0.84, nostalgia: 0.66 },
    themes: ["night", "travel", "bells", "river"],
    image: "/poems/09-song-of-the-pipa.jpg",
    imageAlt: "A small traveling boat beneath fishing lights and a setting moon",
    introduction:
      "A sleepless traveler hears a distant temple bell cross the midnight water. Every image is separated, yet every sound reaches him.",
    interpretation:
      "Melancholy is the condition that makes faraway things feel close: a crow, a fire, a bell, a city outside the dark.",
  }),
  definePoem({
    slug: "on-the-stork-tower",
    title: "On the Stork Tower",
    originalTitle: "登鹳雀楼",
    poet: "Wang Zhihuan",
    poetChinese: "王之涣",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [["白日依山尽", "黄河入海流", "欲穷千里目", "更上一层楼"]],
    translation: [
      [
        "The white sun rests against the mountains and disappears;",
        "the Yellow River runs into the sea.",
        "To widen your view across a thousand miles,",
        "climb one story higher.",
      ],
    ],
    moods: { courage: 0.84, wonder: 0.9, joy: 0.4 },
    themes: ["horizon", "river", "perspective", "ascent"],
    image: "/poems/06-bring-in-the-wine.jpg",
    imageAlt: "A high tower overlooking the Yellow River at sunset",
    introduction:
      "A monumental landscape becomes a compact philosophy of perspective: seeing farther requires one more act of ascent.",
    interpretation:
      "Courage here is incremental. The horizon changes because the viewer chooses to take the next step.",
  }),
  definePoem({
    slug: "early-departure-from-white-emperor-city",
    title: "Early Departure from White Emperor City",
    originalTitle: "早发白帝城",
    poet: "Li Bai",
    poetChinese: "李白",
    dynasty: "Tang dynasty",
    approximateDate: "759",
    originalChinese: [["朝辞白帝彩云间", "千里江陵一日还", "两岸猿声啼不住", "轻舟已过万重山"]],
    translation: [
      [
        "At dawn I leave White Emperor among colored clouds;",
        "a thousand miles to Jiangling, returned in a single day.",
        "From both banks, the apes cry without end—",
        "my light boat has already passed ten thousand mountains.",
      ],
    ],
    moods: { joy: 1, courage: 0.64, wonder: 0.58 },
    themes: ["release", "speed", "river", "journey"],
    image: "/poems/02-long-road.jpg",
    imageAlt: "A light boat moving swiftly through layered river gorges",
    introduction:
      "Traditionally read against Li Bai’s release from exile, the poem turns a difficult river journey into weightless speed.",
    interpretation:
      "Joy is motion after constraint: the mountains remain immense, yet the light boat is already beyond them.",
  }),
  definePoem({
    slug: "seeing-meng-haoran-off",
    title: "Seeing Meng Haoran Off at Yellow Crane Tower",
    originalTitle: "黄鹤楼送孟浩然之广陵",
    poet: "Li Bai",
    poetChinese: "李白",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [["故人西辞黄鹤楼", "烟花三月下扬州", "孤帆远影碧空尽", "唯见长江天际流"]],
    translation: [
      [
        "My old friend leaves the west from Yellow Crane Tower,",
        "down to Yangzhou in the flower-mist of March.",
        "The lone sail’s distant shadow fades into blue sky;",
        "I see only the Yangtze flowing at heaven’s edge.",
      ],
    ],
    moods: { longing: 0.9, nostalgia: 0.62, wonder: 0.52 },
    themes: ["friendship", "farewell", "river", "spring"],
    image: "/poems/08-yellow-crane-tower.jpg",
    imageAlt: "A lone sail disappearing where a wide river meets the sky",
    introduction:
      "The farewell continues after the boat is almost invisible. The watcher’s gaze follows the sail until only the river remains.",
    interpretation:
      "Longing begins before absence is complete—the eye keeps holding the friend after distance has taken him.",
  }),
  definePoem({
    slug: "spring-morning",
    title: "Spring Morning",
    originalTitle: "春晓",
    poet: "Meng Haoran",
    poetChinese: "孟浩然",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [["春眠不觉晓", "处处闻啼鸟", "夜来风雨声", "花落知多少"]],
    translation: [
      [
        "Sleeping in spring, I did not know dawn had come.",
        "Everywhere, I hear birds calling.",
        "Through the night—the sound of wind and rain.",
        "How many blossoms have fallen?",
      ],
    ],
    moods: { joy: 0.78, stillness: 0.56, melancholy: 0.36 },
    themes: ["spring", "waking", "birds", "change"],
    image: "/poems/03-drinking-wine.jpg",
    imageAlt: "Spring blossoms after rain in the soft light of morning",
    introduction:
      "The poem wakes slowly: birds reveal morning, memory reveals rain, and joy turns gently toward the fallen blossoms.",
    interpretation:
      "Joy is made more vivid by impermanence. Spring is precious because the night has already changed it.",
  }),
  definePoem({
    slug: "frontier-song",
    title: "Frontier Song",
    originalTitle: "出塞",
    poet: "Wang Changling",
    poetChinese: "王昌龄",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [["秦时明月汉时关", "万里长征人未还", "但使龙城飞将在", "不教胡马度阴山"]],
    translation: [
      [
        "The moon of Qin, the frontier passes of Han;",
        "from campaigns ten thousand miles away, the soldiers have not returned.",
        "If only the Winged General still guarded Dragon City,",
        "no horse from beyond would cross the Yin Mountains.",
      ],
    ],
    moods: { courage: 1, nostalgia: 0.62, melancholy: 0.4 },
    themes: ["frontier", "war", "memory", "defense"],
    image: "/poems/07-climbing-high.jpg",
    imageAlt: "An ancient frontier pass under a cold moon",
    introduction:
      "Dynasties change, but the same moon shines over the same frontier and the same human cost of war.",
    interpretation:
      "Courage is inseparable from longing for those who have not returned, and from the wish that strength might finally end the loss.",
  }),
  definePoem({
    slug: "summer-quatrain",
    title: "Summer Quatrain",
    originalTitle: "夏日绝句",
    poet: "Li Qingzhao",
    poetChinese: "李清照",
    dynasty: "Song dynasty",
    approximateDate: "12th century",
    originalChinese: [["生当作人杰", "死亦为鬼雄", "至今思项羽", "不肯过江东"]],
    translation: [
      [
        "In life, be a hero among the living;",
        "in death, a champion among ghosts.",
        "Even now, we remember Xiang Yu,",
        "who would not retreat across the eastern river.",
      ],
    ],
    moods: { courage: 1, nostalgia: 0.44 },
    themes: ["integrity", "history", "defiance", "memory"],
    image: "/poems/06-bring-in-the-wine.jpg",
    imageAlt: "Dark river water beneath a fierce band of golden light",
    introduction:
      "Li Qingzhao uses the memory of the defeated general Xiang Yu to make an uncompromising statement about dignity and retreat.",
    interpretation:
      "Courage is measured not by victory but by the line a person refuses to cross.",
  }),
  definePoem({
    slug: "remembering-my-brothers",
    title: "Remembering My Brothers East of the Mountains",
    originalTitle: "九月九日忆山东兄弟",
    poet: "Wang Wei",
    poetChinese: "王维",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [["独在异乡为异客", "每逢佳节倍思亲", "遥知兄弟登高处", "遍插茱萸少一人"]],
    translation: [
      [
        "Alone in a foreign place, a stranger twice over;",
        "at every festival, I miss my family more.",
        "Far away, I know my brothers are climbing high,",
        "each wearing dogwood—one person missing.",
      ],
    ],
    moods: { nostalgia: 1, longing: 0.86, solitude: 0.68 },
    themes: ["family", "festival", "absence", "home"],
    image: "/poems/02-long-road.jpg",
    imageAlt: "A distant mountain path at festival time with one traveler absent",
    introduction:
      "Written by Wang Wei while away from home, the poem imagines a family ritual from the viewpoint of the one empty place within it.",
    interpretation:
      "Nostalgia is doubled: the speaker misses home and imagines home registering his absence in return.",
  }),
  definePoem({
    slug: "mount-lu-waterfall",
    title: "Looking at Mount Lu Waterfall",
    originalTitle: "望庐山瀑布",
    poet: "Li Bai",
    poetChinese: "李白",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [["日照香炉生紫烟", "遥看瀑布挂前川", "飞流直下三千尺", "疑是银河落九天"]],
    translation: [
      [
        "Sunlight on Incense Burner Peak raises violet smoke.",
        "From afar, the waterfall hangs before the river.",
        "Its flying current drops three thousand feet—",
        "as if the Milky Way had fallen from the ninth heaven.",
      ],
    ],
    moods: { wonder: 1, joy: 0.68, courage: 0.48 },
    themes: ["waterfall", "scale", "sky", "imagination"],
    image: "/poems/06-bring-in-the-wine.jpg",
    imageAlt: "A luminous waterfall descending from violet mountain mist",
    introduction:
      "Li Bai’s imagination does not decorate the waterfall; it finds the scale capable of meeting it—the river of stars falling from heaven.",
    interpretation:
      "Wonder is the mind expanding until the earthly and celestial can occupy the same image.",
  }),
  definePoem({
    slug: "prelude-to-water-melody",
    title: "Prelude to Water Melody",
    originalTitle: "水调歌头·明月几时有",
    poet: "Su Shi",
    poetChinese: "苏轼",
    dynasty: "Song dynasty",
    approximateDate: "1076",
    originalChinese: [
      ["明月几时有", "把酒问青天", "不知天上宫阙", "今夕是何年"],
      ["我欲乘风归去", "又恐琼楼玉宇", "高处不胜寒", "起舞弄清影", "何似在人间"],
      ["转朱阁", "低绮户", "照无眠", "不应有恨", "何事长向别时圆"],
      ["人有悲欢离合", "月有阴晴圆缺", "此事古难全", "但愿人长久", "千里共婵娟"],
    ],
    translation: [
      [
        "When did the bright moon first appear?",
        "I raise my wine and ask the blue sky.",
        "In the palaces of heaven,",
        "what year is tonight?",
      ],
      [
        "I would ride the wind and return there,",
        "but fear those towers of jade,",
        "the unbearable cold of such height.",
        "I dance with my clear shadow—",
        "how could heaven be better than the human world?",
      ],
      [
        "The moon turns around the red chamber,",
        "leans through the carved window,",
        "and shines on the sleepless.",
        "Surely it bears no grudge—",
        "why is it always full when people are apart?",
      ],
      [
        "People know joy and sorrow, meeting and parting;",
        "the moon grows bright and dim, round and broken.",
        "Nothing has ever been complete.",
        "May we both live long,",
        "sharing this moonlight across a thousand miles.",
      ],
    ],
    moods: {
      longing: 1,
      wonder: 0.92,
      nostalgia: 0.78,
      melancholy: 0.52,
    },
    themes: ["moon", "family", "distance", "acceptance"],
    image: "/poems/04-spring-river.jpg",
    imageAlt: "A full moon shared across distant night landscapes",
    introduction:
      "Written during Mid-Autumn while separated from his brother, Su Shi moves from cosmic questioning to a humane acceptance of incompleteness.",
    interpretation:
      "Longing is transformed rather than solved: those who cannot meet may still share the same light.",
  }),
  definePoem({
    slug: "plum-blossom",
    title: "Plum Blossom",
    originalTitle: "梅花",
    poet: "Wang Anshi",
    poetChinese: "王安石",
    dynasty: "Song dynasty",
    approximateDate: "11th century",
    originalChinese: [["墙角数枝梅", "凌寒独自开", "遥知不是雪", "为有暗香来"]],
    translation: [
      [
        "At the wall’s corner, a few branches of plum",
        "flower alone against the cold.",
        "From far away I know it is not snow—",
        "a hidden fragrance reaches me.",
      ],
    ],
    moods: { stillness: 0.86, courage: 0.78, wonder: 0.46 },
    themes: ["winter", "fragrance", "resilience", "attention"],
    image: "/poems/03-drinking-wine.jpg",
    imageAlt: "White plum blossoms opening against a dark winter wall",
    introduction:
      "A few blossoms are recognized not by sight but by fragrance, their quiet presence made stronger by winter.",
    interpretation:
      "Courage can be almost invisible: to flower alone, without announcement, in the cold.",
  }),
  definePoem({
    slug: "view-of-mount-tai",
    title: "A View of Mount Tai",
    originalTitle: "望岳",
    poet: "Du Fu",
    poetChinese: "杜甫",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [
      ["岱宗夫如何", "齐鲁青未了", "造化钟神秀", "阴阳割昏晓"],
      ["荡胸生曾云", "决眦入归鸟", "会当凌绝顶", "一览众山小"],
    ],
    translation: [
      [
        "What is Mount Tai like?",
        "Its green has no end across Qi and Lu.",
        "Creation gathered its sacred beauty here;",
        "its shadow divides dusk from dawn.",
      ],
      [
        "Layered clouds rise and widen my chest;",
        "returning birds enter my straining eyes.",
        "One day I will stand upon its highest summit",
        "and see all other mountains become small.",
      ],
    ],
    moods: { wonder: 0.98, courage: 1, joy: 0.42 },
    themes: ["mountains", "ambition", "scale", "ascent"],
    image: "/poems/07-climbing-high.jpg",
    imageAlt: "A vast sacred mountain dividing shadow and morning light",
    introduction:
      "A young Du Fu looks at Mount Tai and turns awe into a vow. The mountain’s scale enlarges rather than diminishes him.",
    interpretation:
      "Courage begins as a way of seeing: the summit is not yet reached, but the future self is already standing there.",
  }),
  definePoem({
    slug: "river-village",
    title: "River Village",
    originalTitle: "江村",
    poet: "Du Fu",
    poetChinese: "杜甫",
    dynasty: "Tang dynasty",
    approximateDate: "760",
    originalChinese: [
      ["清江一曲抱村流", "长夏江村事事幽", "自去自来堂上燕", "相亲相近水中鸥"],
      ["老妻画纸为棋局", "稚子敲针作钓钩", "多病所须唯药物", "微躯此外更何求"],
    ],
    translation: [
      [
        "A bend of clear river embraces the village;",
        "through the long summer, everything here is quiet.",
        "Swallows come and go freely through the hall;",
        "water gulls draw close to one another.",
      ],
      [
        "My old wife draws a chessboard on paper;",
        "my little child hammers a needle into a fishing hook.",
        "In illness, the only thing I still require is medicine.",
        "For this slight body, what more could I ask?",
      ],
    ],
    moods: { stillness: 0.9, joy: 0.76, nostalgia: 0.42 },
    themes: ["family", "summer", "home", "contentment"],
    image: "/poems/05-autumn-evening.jpg",
    imageAlt: "A quiet summer village held by a bend in a clear river",
    introduction:
      "After years of upheaval, Du Fu records an interval of domestic peace: swallows, a handmade game, a child’s fishing hook.",
    interpretation:
      "Joy is modest and therefore durable—the feeling of having enough inside a small, imperfect life.",
  }),
  definePoem({
    slug: "night-rain-sent-north",
    title: "Night Rain Sent North",
    originalTitle: "夜雨寄北",
    poet: "Li Shangyin",
    poetChinese: "李商隐",
    dynasty: "Tang dynasty",
    approximateDate: "9th century",
    originalChinese: [["君问归期未有期", "巴山夜雨涨秋池", "何当共剪西窗烛", "却话巴山夜雨时"]],
    translation: [
      [
        "You ask when I will return; no date is certain.",
        "Night rain in the Ba Mountains swells the autumn pool.",
        "When will we sit together, trimming the west-window candle,",
        "and speak of this night of mountain rain?",
      ],
    ],
    moods: { longing: 1, nostalgia: 0.82, melancholy: 0.7 },
    themes: ["rain", "return", "future memory", "home"],
    image: "/poems/10-jeweled-zither.jpg",
    imageAlt: "Night rain gathering outside a window lit by one candle",
    introduction:
      "The speaker imagines a future reunion in which the present loneliness will already have become a shared memory.",
    interpretation:
      "Longing folds time: tonight’s rain is endured by imagining the night when it can finally be told.",
  }),
  definePoem({
    slug: "liangzhou-song",
    title: "Liangzhou Song",
    originalTitle: "凉州词",
    poet: "Wang Han",
    poetChinese: "王翰",
    dynasty: "Tang dynasty",
    approximateDate: "8th century",
    originalChinese: [["葡萄美酒夜光杯", "欲饮琵琶马上催", "醉卧沙场君莫笑", "古来征战几人回"]],
    translation: [
      [
        "Grape wine glows in cups of luminous jade.",
        "We lift them—but the pipa urges us onto our horses.",
        "If I fall drunk upon the battlefield, do not laugh.",
        "Since ancient times, how many return from war?",
      ],
    ],
    moods: { courage: 0.92, joy: 0.7, melancholy: 0.58 },
    themes: ["wine", "war", "music", "mortality"],
    image: "/poems/06-bring-in-the-wine.jpg",
    imageAlt: "Luminous wine cups beside riders preparing to cross a night desert",
    introduction:
      "Celebration and death occupy the same four lines. The feast is vivid because the riders know it may be their last.",
    interpretation:
      "Courage does not erase fear or mortality; it raises a shining cup in their presence.",
  }),
];

export const poems: Poem[] = [...curatedPoems, ...tangAnthologyPoems];
